name: dapublock_example
description: Example code for the dapublock library.
version: 1.0.1
homepage: https://github.com/mauriciotogneri/dapublock

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  yaml: ^3.1.0